### ISSUE TITLE
macOS version of cp does not have -u flag

### ISSUE THREAD

**Issue by i-am-the-slime** [purerl/purerl_otp_sandbox#1]
This makes `rebar3 compile` fail here. 
If I change `cp` into `rsync` it works. Maybe the option is also not strictly necessary?

**Comment by nwolverson** [comment]
Yeah I think this can just be `cp -p`, the time spent copying the files is not so great I believe, so long as the timestamps end up right it's all the same in the end

**Comment by nwolverson** [comment]
Fixed 84748538ac0d4500939fe15f07b685b6a4f91d39
